# Generated by Django 4.2.25 on 2026-06-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMCHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='https://bmc-host or bare hostname', max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('verify_ssl', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('poll_interval', models.IntegerField(default=300, help_text='Seconds between polls')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['host'],
            },
        ),
    ]
