# Generated by Django 4.2.25 on 2026-06-11 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('power_state', models.CharField(blank=True, max_length=50)),
                ('health', models.CharField(blank=True, max_length=50)),
                ('bios_version', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('total_memory_gib', models.FloatField(blank=True, null=True)),
                ('processor_count', models.IntegerField(blank=True, null=True)),
                ('processor_model', models.CharField(blank=True, max_length=255)),
                ('raw_json', models.JSONField(default=dict)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='hosts.bmchost')),
            ],
            options={
                'ordering': ['-polled_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reading', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('upper_threshold_critical', models.FloatField(blank=True, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='inventory.inventorysnapshot')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=100)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('severity', models.CharField(blank=True, choices=[('OK', 'OK'), ('Warning', 'Warning'), ('Critical', 'Critical')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('created_in_db', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='hosts.bmchost')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'unique_together': {('host', 'entry_id')},
            },
        ),
    ]
